### PR TITLE
Rewrite InfestedLeaves renderer. Probably broke it. Hopefully not. Fingers crossed.

### PR DESCRIPTION
**Pull request by SnakeFang**
- Should cause less lag
- Should take texture of original leaf
- Should appear to transition more smoothly
- Might've hit Ctrl-Shift-F and made Github make it look like I changed
everything in one file
- Transition is a bit slower to start off (It's not already white at
like 25%)
- Everything is probably broken
- Removed Herobrine
- More version numbers because yay

### CODE REVIEW

**Comment by MikeLydeamore** [comment]
Infested leaves should not be a TESR. These will cause enormous amounts of lag in large numbers.

**Comment by SnakeFang** [comment]
The color thing was causing more lag in my worlds. :|

**Comment by MikeLydeamore** [comment]
A TESR will re-render on every frame. The ColorMultiplier is the same method used to render leaves different colors in biomes. All leaves should be updating simultaneously, causing only one mass re-draw per update. If you are getting more lag, can you post some profiling or something similar so I can check?

**Comment by MikeLydeamore** [comment]
Oh, I have realised in one of your other PRs you changed it so they *don't* all update at the same time. That would be why you're getting lag. I will change that.

**Comment by SnakeFang** [comment]
I was getting lag before that, so I changed it a while ago in hopes that it would be slightly better.

**Comment by SnakeFang** [comment]
Although I am having some problems with the TESR right now, so don't actually merge this yet

**Comment by SnakeFang** [comment]
Fixed that problem. Forgot to bind the blocks texture. Lol. I'll see if I can do some performance testing all 3 ways - TESR, BlockColor updating at the same time, and BlockColor updating gradually.

**Comment by SnakeFang** [comment]
Mehhh. All the options seem to perform poorly. But the TESR can render a smooth transition at the same FPS as the BlockColor method can render a quite choppy transition (yes, using the update-all-of-them-at-once strategy). It's up to you though, whatever you'd like to keep. I'd also like to note that the update ticks, and the thing that makes it gradual, both only have effect on server logic in my new code. How often the leaves try to spread when they couldn't last time. Having 30 people on a server all with 200 tile entities all searching 26 blocks around them on one tick probably hurts a little bit.
- Removed Herobrine

**Pull request merged**
