### PR TITLE
Merge all of the things

### PR DESCRIPTION
**Pull request by SnakeFang**
- This time is much less organized sorry
- Herobrine made me forget to make separate commits

### CODE REVIEW

**Comment by MikeLydeamore** [comment]
Can you change branch to 1.9 instead of master please?

**Comment by SnakeFang** [comment]
Oops. There.

**Comment by ExpensiveKoala** [comment]
Why not have the default branch be 1.9 at this point?

**Comment by MikeLydeamore** [comment]
Probably should, will at some point soon.

**Pull request merged**
